### ISSUE TITLE
Issue Bug

### ISSUE THREAD

**Issue by BaileyJames99** [gauthig/greenbutton-influxdb#27]
Windows 11
Latest version of python installed Python 3.11.5
Requirements satisfied

C:\Temp\SCEPython>python greenbutton_import.py -f SCE-Nemfile.sample --nodb
Traceback (most recent call last):
  File "C:\Temp\SCEPython\greenbutton_import.py", line 165, in <module>
    (delivered, generated, metricsout) = parse_data(args.file, args.verbose,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\SCEPython\utilparse.py", line 27, in parse_data
    sce_tou_parse(csv_reader, verbose, metricsout)
  File "C:\Temp\SCEPython\utilparse.py", line 54, in sce_tou_parse
    dt_local = datetime.strptime(util_timestamp[0], '%Y-%m-%d %H:%M:%S')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: Â

**Comment by gauthig** [comment]
Hi, did you install the PIP requirements?
________________________________
From: James Bailey ***@***.***>
Sent: Tuesday, September 19, 2023 10:11 PM
To: gauthig/greenbutton-influxdb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gauthig/greenbutton-influxdb] Issue Bug (Issue #27)


Windows 11
Latest version of python installed Python 3.11.5
Requirements satisfied

C:\Temp\SCEPython>python greenbutton_import.py -f SCE-Nemfile.sample --nodb
Traceback (most recent call last):
File "C:\Temp\SCEPython\greenbutton_import.py", line 165, in
(delivered, generated, metricsout) = parse_data(args.file, args.verbose,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Temp\SCEPython\utilparse.py", line 27, in parse_data
sce_tou_parse(csv_reader, verbose, metricsout)
File "C:\Temp\SCEPython\utilparse.py", line 54, in sce_tou_parse
dt_local = datetime.strptime(util_timestamp[0], '%Y-%m-%d %H:%M:%S')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib_strptime.py", line 568, in _strptime_datetime
tt, fraction, gmtoff_fraction = _strptime(data_string, format)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib_strptime.py", line 352, in _strptime
raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: Â

**Comment by BaileyJames99** [comment]
Yes!!!
